import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/providers/theme-provider";
import { Toaster } from "@/components/ui/sonner"
import { AlertTriangle, Check, Info, X } from "lucide-react";
const inter = Inter({
  subsets: ['latin'],
  variable: '--font-sans',
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${inter.variable} font-sans antialiased h-[100vh]`}>
        <ThemeProvider>
          {children}
          <Toaster icons={
            {
              success: <Check className="h-4 w-4 text-green-400" />,
              error: <X className="h-4 w-4 text-red-400" />,
              warning: <AlertTriangle className="h-4 w-4 text-yellow-400" />,
              info: <Info className="h-4 w-4 text-blue-400" />,
            }
          } />
        </ThemeProvider>
      </body>
    </html>
  );
}
